alt-tab alarm, not verified for mobile (I love you<3)
mafia-rust/mafia pull request #458
Opened 2024-02-16 01:02 UTC by Frogz9000

2024-02-16 16:57 UTC, Jack-Papel requested changes

2024-02-16 16:57 UTC, Jack-Papel commented on client/src/index.tsx
> +import { collapseTextChangeRangesAcrossMultipleVersions } from 'typescript';
Unused import
```suggestion
```

2024-02-16 16:57 UTC, Jack-Papel commented on client/src/index.tsx
> +})
Should go in `Anchor` `onComponentMount` function

2024-02-16 16:57 UTC, Jack-Papel commented on client/src/index.tsx
> +})
Or inline these Anchor.onBlur and Anchor.onFocus functions.

2024-03-08 13:58 UTC, Frogz9000 commented
This should be made into a pull request draft :)

2024-04-25 23:12 UTC, Jack-Papel commented
Stale

2024-04-25 23:12 UTC, closed without merging